version: "3.8"

services:

  data:
    container_name: MsSqlServer
    hostname: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrong(!)Password123
    restart: unless-stopped
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - CookingRecipesSystem-network

  server:
    container_name: ServerStartup
    image: borislavgeorgievgeorgiev/cooking-recipes-system-server:1.1
    build:
      context: ./
      dockerfile: Server/src/Startup/Dockerfile
    ports:
      - "6000:80"
      - "6001:443"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql-server;Database=CookingRecipesDB;User=sa;Password=MyStrong(!)Password123;MultipleActiveResultSets=true;
    restart: unless-stopped
    depends_on:
      - "data"
    networks:
      - CookingRecipesSystem-network

  client:
    container_name: ClientStartup
    image: borislavgeorgievgeorgiev/cooking-recipes-system-client:1.01
    build:
      context: ./
      dockerfile: Client/src/Startup/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - "server"
    networks:
      - CookingRecipesSystem-network

networks:
  CookingRecipesSystem-network:


volumes:
  mssqldata:
